import "./globals.css";
import localFont from "next/font/local";

const MSFont = localFont({ src: "../public/fonts/ms-sans-serif.ttf" });

export const metadata = {
  title: "Shopping List",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={MSFont.className}>{children}</body>
    </html>
  );
}
